### ISSUE TITLE
api.Get(queue): failed:  (status: 303 See Other): invalid status code, <200\|\|>299: | stdout

### ISSUE THREAD

**Issue by cemzer** [hotio/unpackerr#20]
Hello guys, I have this error and I cant understand why:
`2021/09/10 21:37:26 [ERROR] Radarr (http://radarr:7878):api.Get(queue): failed:  (status: 303 See Other): invalid status code, <200\|\|>299: | stdout`
Also I dont find anyone having this issue on google so I might have made a dumb mistake while doing the setup onf the container.

Can anyone help me ?

**Comment by mrhotio** [comment]
not a docker image issue
